classDiagram
  class Classification {
    name
  }
  class ColorLogger {
    format(record)
  }
  class Configs {
    drone
    kinect
    myoband
    orchestrator
    robot_arm
  }
  class Drone {
    takeoff_alt
    connect()
    disconnect()
    runScriptMode(cmds)
    sendCommand(cmd, wait_time, expect_multi, end_keyword)
  }
  class DroneConfig {
    baud_rate : int
    debug_mode : bool
    enable : bool
    port : str
    takeoff_alt : int
    verbose : bool
  }
  class Kinect {
    left_pos : NoneType
    right_pos : NoneType
    connect()
    disconnect()
    loop()
  }
  class KinectConfig {
    enable : bool
    verbose : bool
  }
  class MyoUdp {
    data_block : NoneType, ndarray
    connect()
    disconnect()
    get_rotation_matrix()
    loop()
    quaternion_to_rotation_matrix(q)
  }
  class MyoUdpConfig {
    enable : bool
    input_freq : float
    ip : str
    port1 : int
    port2 : int
    sample_freq : float
    verbose : bool
  }
  class Myoband {
    classification : ELBOW_EXT, GRASP, UNKNOWN, WRIST_EXT, WRIST_FLEX, WRIST_ROT_IN, WRIST_ROT_OUT
    connect()
    disconnect()
    loop()
  }
  class MyobandConfig {
    enable : bool
    host : str
    port : int
    verbose : bool
  }
  class Orchestrator {
    drone
    kinect
    myoband
    polling_period : int
    verbose : bool
    connect()
    disconnect()
    get_status()
    loop()
    run_calculations(desired_pos)
    send_output(cmds)
  }
  class OrchestratorConfig {
    polling_period : int
    verbose : bool
  }
  class RobotArmConfig {
    base_height : float
    enable : bool
    link_lengths : List[float]
    verbose : bool
  }
  Drone --* Orchestrator : drone
  Kinect --* Orchestrator : kinect
  Myoband --* Orchestrator : myoband
  DroneConfig --* Configs : drone
  KinectConfig --* Configs : kinect
  MyobandConfig --* Configs : myoband
  OrchestratorConfig --* Configs : orchestrator
  RobotArmConfig --* Configs : robot_arm
