classDiagram
  class Arm {
    current_pose : SE3
    get_ikine()
  }
  class ArmConfig {
    enable : bool
    verbose : bool
  }
  class Classification {
    name
  }
  class ColorLogger {
    format(record)
  }
  class Configs {
    arm
    drone
    kinect
    myoband
    orchestrator
  }
  class Drone {
    takeoff_alt
    connect()
    disconnect()
    isArmable()
    runScriptMode(cmds)
    sendCommand(cmd, wait_time, expect_multi, end_keyword, overwrite_mode)
    sendCommandAsync(cmd, wait_time, expect_multi, end_keyword, overwrite_mode)
  }
  class DroneConfig {
    baud_rate : int
    debug_mode : bool
    enable : bool
    port : str
    takeoff_alt : int
    verbose : bool
  }
  class Kinect {
    left_pos : NoneType
    right_pos : NoneType
    connect()
    disconnect()
    loop()
  }
  class KinectConfig {
    enable : bool
    verbose : bool
  }
  class MyoUdp {
    data_block : NoneType, ndarray
    connect()
    disconnect()
    get_rotation_matrix()
    loop()
    quaternion_to_rotation_matrix(q)
  }
  class MyoUdpConfig {
    enable : bool
    input_freq : float
    ip : str
    port1 : int
    port2 : int
    sample_freq : float
    verbose : bool
  }
  class Myoband {
    classification : GRASP_SPRAY, UNKNOWN, WRIST_ABD_ARM_UP, WRIST_ADD_ARM_DOWN, WRIST_EXT_TURN_RIGHT, WRIST_FLEX_TURN_LEFT
    connect()
    disconnect()
    loop()
  }
  class MyobandConfig {
    enable : bool
    host : str
    port : int
    verbose : bool
  }
  class Orchestrator {
    arm
    drone
    kinect
    myoband
    polling_period : int
    prev_pos
    verbose : bool
    connect()
    disconnect()
    get_status()
    loop()
    run_calculations()
    send_output(cmds)
  }
  class OrchestratorConfig {
    polling_period : int
    verbose : bool
  }
  Arm --* Orchestrator : arm
  Drone --* Orchestrator : drone
  Kinect --* Orchestrator : kinect
  Myoband --* Orchestrator : myoband
  ArmConfig --* Configs : arm
  DroneConfig --* Configs : drone
  KinectConfig --* Configs : kinect
  MyobandConfig --* Configs : myoband
  OrchestratorConfig --* Configs : orchestrator
