classDiagram
  class Classifier {
    classify()
  }
  class Configs {
    drone
    kinect
    motion
    myoband
    robot_arm
  }
  class Drone {
    baud_rate
    debug_mode
    port
    ser : Serial
    speed
    takeoff_alt
    connect()
    disconnect()
    runScriptMode(cmds)
    sendCommand(cmd, wait_time, expect_multi, end_keyword)
  }
  class DroneConfig {
    baud_rate : int
    port : str
    takeoff_alt : int
  }
  class Kinect {
    connect()
    disconnect()
    getPosition()
  }
  class KinectConfig {
    config_placeholder : bool
  }
  class MotionConfig {
    debug_mode : int
    speed : str
  }
  class Myoband {
    connect()
    disconnect()
    getData()
  }
  class MyobandConfig {
    input_freq : float
    ip : str
    port1 : int
    port2 : int
    sample_freq : float
    verbose : bool
  }
  class Orchestrator {
    classifier
    configs
    drone
    kinect
    myoband : Myoband
    connect()
    disconnect()
    get_status()
    poll_sensors()
    run_calculations(desired_pos)
    send_output(cmds)
  }
  class RobotArmConfig {
    base_height : float
    link_lengths : List[float]
  }
  Classifier --* Orchestrator : classifier
  Drone --* Orchestrator : drone
  Kinect --* Orchestrator : kinect
  Myoband --* Orchestrator : myoband
  Configs --* Orchestrator : configs
  DroneConfig --* Configs : drone
  KinectConfig --* Configs : kinect
  MotionConfig --* Configs : motion
  MyobandConfig --* Configs : myoband
  RobotArmConfig --* Configs : robot_arm
