classDiagram
  class src {
  }
  class classifier {
  }
  class classifier {
  }
  class drone {
  }
  class drone {
  }
  class kinematics {
  }
  class forward {
  }
  class inverse {
  }
  class orchestrator {
  }
  class sensors {
  }
  class kinect {
  }
  class myo_listener {
  }
  class myo_udp {
  }
  class utils {
  }
  class config_loader {
  }
  class dataclasses {
  }
  class logger {
  }
  classifier --> classifier
  drone --> drone
  drone --> utils
  kinematics --> forward
  kinematics --> inverse
  orchestrator --> drone
  orchestrator --> sensors
  orchestrator --> utils
  sensors --> kinect
  sensors --> myo_listener
  kinect --> utils
  myo_listener --> classifier
  myo_listener --> utils
  myo_udp --> utils
  utils --> config_loader
  utils --> logger
  config_loader --> dataclasses
  dataclasses --> dataclasses
