drone:
  port: "COM10"
  baud_rate: 57600
  takeoff_alt: 2
  verbose: true
  debug_mode: true
  enable: false

robot_arm:
  base_height: 0.05
  link_lengths: [0.2, 0.2]
  verbose: true
  enable: false

myoudp:
  ip: "192.168.1.10"
  port1: 15001
  port2: 15002
  sample_freq: 1000.0
  input_freq: 200.0
  verbose: true
  enable: false

myoband:
  host: "localhost"
  port: 65432
  verbose: true
  enable: true

kinect:
  verbose: true
  enable: true

orchestrator:
  verbose: true
  polling_period: 1